import json
import boto3
import psycopg2
#def getCredentials():
# see above
def handler(event, context):
  credential = getCredentials()
  connection = psycopg2.connect(user=credential['username'], password=credential['password'], host=credential['host'], database=credential['db'])
  cursor = connection.cursor()
  query = '''--initial database
    CREATE DATABASE postgrelearning;

    --create a schema
    CREATE SCHEMA sales;

    --show the search path for schemas
    SHOW search_path;

    --modify the search path
    SET search_path TO sales,public;


    --create a table with defaults and calculated column
    CREATE TABLE sales.saledetail
    (saledetailid int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    saledatetime TIMESTAMP DEFAULT NOW(),
    itemtotal MONEY,
    itemdiscount NUMERIC(2,2),
    saletotal MONEY GENERATED ALWAYS AS (itemtotal * itemdiscount) STORED,
    CONSTRAINT saledetailpk PRIMARY KEY (saledetailid));

    -- add data to the table
    INSERT INTO sales.saledetail
    (itemtotal,itemdiscount)
    VALUES
    (343.42,.95);

    -- retrieve the data
    SELECT * FROM sales.saledetail;
    '''
  cursor.execute(query)
  results = cursor.fetchone()
  cursor.close()
  connection.commit()
  return results